disp_data/urls.py
from django.contrib import admin
from django.urls import path
from disp_data import views

app_name = 'disp_data'

urlpatterns = [
    path('', views.my_view, name='ourhome'),   
]

table/urls.py
from django.contrib import admin
from django.urls import path, include
from disp_data import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('disp_data/', include('disp_data.urls'), name='home'),
    path('',views.button, name='button')
]

disp_data/models.py
from django.db import models

# Create your models here.
class Student3(models.Model):
	firstname = models.CharField(max_length=100,unique=False)
	start_time = models.CharField(max_length=100,unique=False)
	phone_no = models.CharField(max_length=10,unique=False)
	res_id = models.IntegerField(unique=False)
	

disp_data/views.py
from django.shortcuts import render
from django.http import HttpResponse
from disp_data.models import Student3
from . import script1
#from script1 import first_name,start_time,phone_no,res_id

# Create your views here.
def button(request):
    return render(request,'button.html')



'''def disp_home(request):
    data = Student.objects.all()

    stu = {
        "student_number": data
    }

    return render(request, 'disp_data/data.html', context = stu)
    #return render_to_response("login/profile.html", stu)

from django.shortcuts import render
from .models import Student    # Student is the model class defined in models.py'''

# Assuming the data to be entered is presnet in these lists
'''stud_name = ['Aman', 'Vijay']
stud_age = [13, 12]
stud_marks = [20, 22]

first_name =[]
start_time = []
phone_no = []
res_id = []'''

def my_view(request, *args, **kwargs):

    # Iterate through all the data items
    test_result = Student3.objects.all();
    if len(test_result)==0:
        for i in range(len(script1.first_name)):
        # Insert in the database
            Student3.objects.create(firstname = script1.first_name[i], start_time = script1.start_time[i], phone_no = script1.phone_no[i], res_id = script1.res_id[i])


    # Getting all the stuff from database
    query_results = Student3.objects.all();

    # Creating a dictionary to pass as an argument
    context = { 'query_results' : query_results }

    # Returning the rendered html
    return render(request, "disp_data/data.html", context)

templates/button.html
<!DOCTYPE html>
<html>
	<head>
		<title>Home</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	
	<body>
		<div class='jumbotron'>
		<h1>To view the Dashboard</h1>
		<button type="button" class="btn btn-warning"><a href="{% url 'disp_data:ourhome' %}">Click here!</a></button>
		</div>

	</body>
</html>

templates/disp_data/data.html
<!DOCTYPE html>
<html>
	<head>
		<title>Students' Data</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">			
		<meta name="description" content="Bootstrap.">  
		<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">   
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
		<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>		
	</head>
	
	<body>
	<body style="margin:20px auto">  
		<div class="container">
		<div class="row header" style="text-align:center;color:red">
		<h1>Student Record</h1>
		</div>
		
		

		<dic class="djangotwo">
			{% if query_results %}
				<table id="myTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
					
					<thead>
						<th class="th-sm">First Name</th>
						<th class="th-sm">Start Time</th>
						<th class="th-sm">Phone Number</th>
						<th class="th-sm">Reservation Id</th>
					</thead>


					{% for std in query_results %}
					<tr>
						<td>{{ std.firstname }}</td>
						<td>{{ std.start_time }}</td>
						<td>{{ std.phone_no }}</td>
						<td>{{ std.res_id }}</td>
					</tr>
					{% endfor %}

					
				</table>
			{% else %}
				<p>No Student Records found</p>
			{% endif %}
		</dic>
		</div>
		
	</body>
	<script>
	$(document).ready(function(){
	    $('#myTable').DataTable( {
        "ordering": false,
        "info":     false
    	} );

	});
	</script>
</html>

templates/disp_data/data1.html
<!DOCTYPE html>
<html>
	<head>
		<title>Students' Data</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">			
		<meta name="description" content="Bootstrap.">  
		<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">   
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
		<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>		
	</head>
	
	<body>
	<body style="margin:20px auto">  
		<div class="container">
		<div class="row header" style="text-align:center;color:red">
		<h1>Student Record</h1>
		</div>
		
		

		<dic class="djangotwo">
			{% if query_results %}
				<table id="myTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
					
					<thead>
						<th class="th-sm">First Name</th>
						<th class="th-sm">Start Time</th>
						<th class="th-sm">Phone Number</th>
						<th class="th-sm">Reservation Id</th>
					</thead>


					{% for std in query_results %}
					<tr>
						<td>{{ std.firstname }}</td>
						<td>{{ std.start_time }}</td>
						<td>{{ std.phone_no }}</td>
						<td>{{ std.res_id }}</td>
					</tr>
					{% endfor %}

					
				</table>
			{% else %}
				<p>No Student Records found</p>
			{% endif %}
		</dic>
		</div>
		
	</body>
	<script>
	$(document).ready(function(){
	    $('#myTable').DataTable( {
        "ordering": false,
        "info":     false
    	} );

	});
	</script>
</html>